export const CITY = [
    "Abhava",
    "Abrama",
    "Adajan",
    "Althan",
    "Amroli",
    "Bamroli",
    "Bharthana – Vesu",
    "Bhatar",
    "Bhestan",
    "Bhimrad",
    "Dindoli",
    "Dumas",
    "Godadara",
    "Gopipura",
    "Harinagar Udhna",
    "Ichhapor",
    "Jahangirpura",
    "Kapodra Circle",
    "Katargam",
    "Kathor",
    "Kathor Ward",
    "Khatodara",
    "Kumbhariya",
    "Lambe Hanuman Road",
    "Limbayat",
    "MAJURA",
    "Magdalla",
    "Mahidharpura",
    "Nanpura",
    "Pal",
    "Palanpor",
    "Parvat",
    "Piplod",
    "Puna",
    "Rundh",
    "Sachin",
    "Sagrampura",
    "Saroli",
    "Sarsana",
    "Simada",
    "Udhana",
    "Umara",
    "Varachha - Mota Varachha",
    "Varachha - Nana Varachha",
    "Varachha - Sarthana",
    "Varachha Main",
    "Vesu",
    "Vesu Canal Road",
    "Vesu-Abhwa Road",
  ] as const;
  